### ISSUE TITLE
脚本报错

### ISSUE THREAD

**Issue by pt001** [3ndz/Shiro-721#1]
脚本报错：
Traceback (most recent call last):
  File "shiro_exp.py", line 63, in <module>
    enc = padbuster.encrypt(plaintext=payload, block_size=16)
  File "/root/Shiro-721/exp/paddingoracle.py", line 94, in encrypt
    **kwargs)
  File "/root/Shiro-721/exp/paddingoracle.py", line 261, in bust
    byte_num, block, self.max_retries))
RuntimeError: Could not decrypt byte 15 in bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00') within maximum allotted retries (3)

**Comment by inspiringz** [comment]
我这里自测没问题的，该 exp 来自 https://github.com/wuppp/shiro_rce_exp
